# CMake generated Testfile for 
# Source directory: /home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common
# Build directory: /home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BitFieldTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/BitFieldTest.elf")
set_tests_properties(BitFieldTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;1;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BitSetTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/BitSetTest.elf")
set_tests_properties(BitSetTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;2;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BitUtilsTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/BitUtilsTest.elf")
set_tests_properties(BitUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;3;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BlockingLoopTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/BlockingLoopTest.elf")
set_tests_properties(BlockingLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;4;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(BusyLoopTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/BusyLoopTest.elf")
set_tests_properties(BusyLoopTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;5;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(CommonFuncsTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/CommonFuncsTest.elf")
set_tests_properties(CommonFuncsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;6;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(CryptoEcTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/CryptoEcTest.elf")
set_tests_properties(CryptoEcTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;7;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(CryptoSHA1Test "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/CryptoSHA1Test.elf")
set_tests_properties(CryptoSHA1Test PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;8;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(EnumFormatterTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/EnumFormatterTest.elf")
set_tests_properties(EnumFormatterTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;9;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(EventTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/EventTest.elf")
set_tests_properties(EventTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;10;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FileUtilTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/FileUtilTest.elf")
set_tests_properties(FileUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;11;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FixedSizeQueueTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/FixedSizeQueueTest.elf")
set_tests_properties(FixedSizeQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;12;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FlagTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/FlagTest.elf")
set_tests_properties(FlagTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;13;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(FloatUtilsTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/FloatUtilsTest.elf")
set_tests_properties(FloatUtilsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;14;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(MathUtilTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/MathUtilTest.elf")
set_tests_properties(MathUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;15;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(NandPathsTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/NandPathsTest.elf")
set_tests_properties(NandPathsTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;16;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(SPSCQueueTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/SPSCQueueTest.elf")
set_tests_properties(SPSCQueueTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;17;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(StringUtilTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/StringUtilTest.elf")
set_tests_properties(StringUtilTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;18;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
add_test(SwapTest "/home/ev/ClangProjects/dolphin-switch/Binaries/Tests/SwapTest.elf")
set_tests_properties(SwapTest PROPERTIES  _BACKTRACE_TRIPLES "/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/CMakeLists.txt;23;add_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;19;add_dolphin_test;/home/ev/ClangProjects/dolphin-switch/Source/UnitTests/Common/CMakeLists.txt;0;")
