# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_7Z "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "ON")
set(CPACK_BINARY_NUGET "OFF")
set(CPACK_BINARY_WIX "OFF")
set(CPACK_BINARY_ZIP "OFF")
set(CPACK_BUILD_SOURCE_DIRS "/home/ev/ClangProjects/dolphin-switch;/home/ev/ClangProjects/dolphin-switch")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_SECTION "Games")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "dolphin-emu built using CMake")
set(CPACK_GENERATOR "TGZ;TBZ2;ZIP")
set(CPACK_IGNORE_FILES "\\.#;/#;.*~;\\.swp;/\\.git;/home/ev/ClangProjects/dolphin-switch")
set(CPACK_INSTALLED_DIRECTORIES "/home/ev/ClangProjects/dolphin-switch;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/opt/devkitpro/portlibs/switch")
set(CPACK_MODULE_PATH "/opt/devkitpro/cmake;/home/ev/ClangProjects/dolphin-switch/CMake")
set(CPACK_NSIS_DISPLAY_NAME "dolphin-emu 5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "dolphin-emu 5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/ev/ClangProjects/dolphin-switch/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/ev/ClangProjects/dolphin-switch/Data/cpack_package_description.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A GameCube and Wii emulator")
set(CPACK_PACKAGE_FILE_NAME "dolphin-emu-5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "dolphin-emu 5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "dolphin-emu 5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_PACKAGE_NAME "dolphin-emu")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Dolphin Team")
set(CPACK_PACKAGE_VERSION "5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_PACKAGE_VERSION_MAJOR "5")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "376d0afad8ad5b4c049c4963e1a885802f0add8b")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.22/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.22/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_GROUP "System/Emulators/Other")
set(CPACK_RPM_PACKAGE_LICENSE "GPL-2.0")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TGZ;TBZ2;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "\\.#;/#;.*~;\\.swp;/\\.git;/home/ev/ClangProjects/dolphin-switch")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/ev/ClangProjects/dolphin-switch;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/ev/ClangProjects/dolphin-switch/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "dolphin-emu-5.0.376d0afad8ad5b4c049c4963e1a885802f0add8b-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "NintendoSwitch-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "NintendoSwitch")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "NintendoSwitch-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/ev/ClangProjects/dolphin-switch/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
