# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ev/ClangProjects/dolphin-switch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ev/ClangProjects/dolphin-switch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/cpack --config ./CPackSourceConfig.cmake /home/ev/ClangProjects/dolphin-switch/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/ev/Documents/clion-2020.1/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ev/ClangProjects/dolphin-switch/CMakeFiles /home/ev/ClangProjects/dolphin-switch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ev/ClangProjects/dolphin-switch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cpp-optparse

# Build rule for target.
cpp-optparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp-optparse
.PHONY : cpp-optparse

# fast build rule for target.
cpp-optparse/fast:
	$(MAKE) -f Externals/cpp-optparse/CMakeFiles/cpp-optparse.dir/build.make Externals/cpp-optparse/CMakeFiles/cpp-optparse.dir/build
.PHONY : cpp-optparse/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) -f Externals/fmt/CMakeFiles/fmt.dir/build.make Externals/fmt/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) -f Externals/imgui/CMakeFiles/imgui.dir/build.make Externals/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named implot

# Build rule for target.
implot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 implot
.PHONY : implot

# fast build rule for target.
implot/fast:
	$(MAKE) -f Externals/implot/CMakeFiles/implot.dir/build.make Externals/implot/CMakeFiles/implot.dir/build
.PHONY : implot/fast

#=============================================================================
# Target rules for targets named glslang

# Build rule for target.
glslang: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glslang
.PHONY : glslang

# fast build rule for target.
glslang/fast:
	$(MAKE) -f Externals/glslang/CMakeFiles/glslang.dir/build.make Externals/glslang/CMakeFiles/glslang.dir/build
.PHONY : glslang/fast

#=============================================================================
# Target rules for targets named pugixml

# Build rule for target.
pugixml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pugixml
.PHONY : pugixml

# fast build rule for target.
pugixml/fast:
	$(MAKE) -f Externals/pugixml/CMakeFiles/pugixml.dir/build.make Externals/pugixml/CMakeFiles/pugixml.dir/build
.PHONY : pugixml/fast

#=============================================================================
# Target rules for targets named enet

# Build rule for target.
enet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 enet
.PHONY : enet

# fast build rule for target.
enet/fast:
	$(MAKE) -f Externals/enet/CMakeFiles/enet.dir/build.make Externals/enet/CMakeFiles/enet.dir/build
.PHONY : enet/fast

#=============================================================================
# Target rules for targets named xxhash

# Build rule for target.
xxhash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xxhash
.PHONY : xxhash

# fast build rule for target.
xxhash/fast:
	$(MAKE) -f Externals/xxhash/CMakeFiles/xxhash.dir/build.make Externals/xxhash/CMakeFiles/xxhash.dir/build
.PHONY : xxhash/fast

#=============================================================================
# Target rules for targets named bzip2

# Build rule for target.
bzip2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bzip2
.PHONY : bzip2

# fast build rule for target.
bzip2/fast:
	$(MAKE) -f Externals/bzip2/CMakeFiles/bzip2.dir/build.make Externals/bzip2/CMakeFiles/bzip2.dir/build
.PHONY : bzip2/fast

#=============================================================================
# Target rules for targets named lzma

# Build rule for target.
lzma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lzma
.PHONY : lzma

# fast build rule for target.
lzma/fast:
	$(MAKE) -f Externals/liblzma/CMakeFiles/lzma.dir/build.make Externals/liblzma/CMakeFiles/lzma.dir/build
.PHONY : lzma/fast

#=============================================================================
# Target rules for targets named zstd

# Build rule for target.
zstd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zstd
.PHONY : zstd

# fast build rule for target.
zstd/fast:
	$(MAKE) -f Externals/zstd/CMakeFiles/zstd.dir/build.make Externals/zstd/CMakeFiles/zstd.dir/build
.PHONY : zstd/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f Externals/zlib-ng/zlib-ng/CMakeFiles/zlib.dir/build.make Externals/zlib-ng/zlib-ng/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named minizip

# Build rule for target.
minizip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minizip
.PHONY : minizip

# fast build rule for target.
minizip/fast:
	$(MAKE) -f Externals/minizip/CMakeFiles/minizip.dir/build.make Externals/minizip/CMakeFiles/minizip.dir/build
.PHONY : minizip/fast

#=============================================================================
# Target rules for targets named lzo2

# Build rule for target.
lzo2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lzo2
.PHONY : lzo2

# fast build rule for target.
lzo2/fast:
	$(MAKE) -f Externals/LZO/CMakeFiles/lzo2.dir/build.make Externals/LZO/CMakeFiles/lzo2.dir/build
.PHONY : lzo2/fast

#=============================================================================
# Target rules for targets named spng

# Build rule for target.
spng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 spng
.PHONY : spng

# fast build rule for target.
spng/fast:
	$(MAKE) -f Externals/libspng/CMakeFiles/spng.dir/build.make Externals/libspng/CMakeFiles/spng.dir/build
.PHONY : spng/fast

#=============================================================================
# Target rules for targets named FreeSurround

# Build rule for target.
FreeSurround: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FreeSurround
.PHONY : FreeSurround

# fast build rule for target.
FreeSurround/fast:
	$(MAKE) -f Externals/FreeSurround/CMakeFiles/FreeSurround.dir/build.make Externals/FreeSurround/CMakeFiles/FreeSurround.dir/build
.PHONY : FreeSurround/fast

#=============================================================================
# Target rules for targets named SoundTouch

# Build rule for target.
SoundTouch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SoundTouch
.PHONY : SoundTouch

# fast build rule for target.
SoundTouch/fast:
	$(MAKE) -f Externals/soundtouch/CMakeFiles/SoundTouch.dir/build.make Externals/soundtouch/CMakeFiles/SoundTouch.dir/build
.PHONY : SoundTouch/fast

#=============================================================================
# Target rules for targets named cubeb

# Build rule for target.
cubeb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cubeb
.PHONY : cubeb

# fast build rule for target.
cubeb/fast:
	$(MAKE) -f Externals/cubeb/CMakeFiles/cubeb.dir/build.make Externals/cubeb/CMakeFiles/cubeb.dir/build
.PHONY : cubeb/fast

#=============================================================================
# Target rules for targets named speex

# Build rule for target.
speex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 speex
.PHONY : speex

# fast build rule for target.
speex/fast:
	$(MAKE) -f Externals/cubeb/CMakeFiles/speex.dir/build.make Externals/cubeb/CMakeFiles/speex.dir/build
.PHONY : speex/fast

#=============================================================================
# Target rules for targets named sfml-network

# Build rule for target.
sfml-network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfml-network
.PHONY : sfml-network

# fast build rule for target.
sfml-network/fast:
	$(MAKE) -f Externals/SFML/CMakeFiles/sfml-network.dir/build.make Externals/SFML/CMakeFiles/sfml-network.dir/build
.PHONY : sfml-network/fast

#=============================================================================
# Target rules for targets named sfml-system

# Build rule for target.
sfml-system: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfml-system
.PHONY : sfml-system

# fast build rule for target.
sfml-system/fast:
	$(MAKE) -f Externals/SFML/CMakeFiles/sfml-system.dir/build.make Externals/SFML/CMakeFiles/sfml-system.dir/build
.PHONY : sfml-system/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f Externals/mbedtls/library/CMakeFiles/lib.dir/build.make Externals/mbedtls/library/CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named mbedtls

# Build rule for target.
mbedtls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedtls
.PHONY : mbedtls

# fast build rule for target.
mbedtls/fast:
	$(MAKE) -f Externals/mbedtls/library/CMakeFiles/mbedtls.dir/build.make Externals/mbedtls/library/CMakeFiles/mbedtls.dir/build
.PHONY : mbedtls/fast

#=============================================================================
# Target rules for targets named mbedx509

# Build rule for target.
mbedx509: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedx509
.PHONY : mbedx509

# fast build rule for target.
mbedx509/fast:
	$(MAKE) -f Externals/mbedtls/library/CMakeFiles/mbedx509.dir/build.make Externals/mbedtls/library/CMakeFiles/mbedx509.dir/build
.PHONY : mbedx509/fast

#=============================================================================
# Target rules for targets named mbedcrypto

# Build rule for target.
mbedcrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedcrypto
.PHONY : mbedcrypto

# fast build rule for target.
mbedcrypto/fast:
	$(MAKE) -f Externals/mbedtls/library/CMakeFiles/mbedcrypto.dir/build.make Externals/mbedtls/library/CMakeFiles/mbedcrypto.dir/build
.PHONY : mbedcrypto/fast

#=============================================================================
# Target rules for targets named iconv

# Build rule for target.
iconv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconv
.PHONY : iconv

# fast build rule for target.
iconv/fast:
	$(MAKE) -f Externals/libiconv-1.14/CMakeFiles/iconv.dir/build.make Externals/libiconv-1.14/CMakeFiles/iconv.dir/build
.PHONY : iconv/fast

#=============================================================================
# Target rules for targets named FatFs

# Build rule for target.
FatFs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FatFs
.PHONY : FatFs

# fast build rule for target.
FatFs/fast:
	$(MAKE) -f Externals/FatFs/CMakeFiles/FatFs.dir/build.make Externals/FatFs/CMakeFiles/FatFs.dir/build
.PHONY : FatFs/fast

#=============================================================================
# Target rules for targets named rcheevos

# Build rule for target.
rcheevos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rcheevos
.PHONY : rcheevos

# fast build rule for target.
rcheevos/fast:
	$(MAKE) -f Externals/rcheevos/CMakeFiles/rcheevos.dir/build.make Externals/rcheevos/CMakeFiles/rcheevos.dir/build
.PHONY : rcheevos/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f Externals/gtest/googlemock/CMakeFiles/gmock.dir/build.make Externals/gtest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f Externals/gtest/googlemock/CMakeFiles/gmock_main.dir/build.make Externals/gtest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f Externals/gtest/googletest/CMakeFiles/gtest.dir/build.make Externals/gtest/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f Externals/gtest/googletest/CMakeFiles/gtest_main.dir/build.make Externals/gtest/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named audiocommon

# Build rule for target.
audiocommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 audiocommon
.PHONY : audiocommon

# fast build rule for target.
audiocommon/fast:
	$(MAKE) -f Source/Core/AudioCommon/CMakeFiles/audiocommon.dir/build.make Source/Core/AudioCommon/CMakeFiles/audiocommon.dir/build
.PHONY : audiocommon/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f Source/Core/Common/CMakeFiles/common.dir/build.make Source/Core/Common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f Source/Core/Core/CMakeFiles/core.dir/build.make Source/Core/Core/CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named discio

# Build rule for target.
discio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 discio
.PHONY : discio

# fast build rule for target.
discio/fast:
	$(MAKE) -f Source/Core/DiscIO/CMakeFiles/discio.dir/build.make Source/Core/DiscIO/CMakeFiles/discio.dir/build
.PHONY : discio/fast

#=============================================================================
# Target rules for targets named inputcommon

# Build rule for target.
inputcommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputcommon
.PHONY : inputcommon

# fast build rule for target.
inputcommon/fast:
	$(MAKE) -f Source/Core/InputCommon/CMakeFiles/inputcommon.dir/build.make Source/Core/InputCommon/CMakeFiles/inputcommon.dir/build
.PHONY : inputcommon/fast

#=============================================================================
# Target rules for targets named uicommon

# Build rule for target.
uicommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uicommon
.PHONY : uicommon

# fast build rule for target.
uicommon/fast:
	$(MAKE) -f Source/Core/UICommon/CMakeFiles/uicommon.dir/build.make Source/Core/UICommon/CMakeFiles/uicommon.dir/build
.PHONY : uicommon/fast

#=============================================================================
# Target rules for targets named videocommon

# Build rule for target.
videocommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videocommon
.PHONY : videocommon

# fast build rule for target.
videocommon/fast:
	$(MAKE) -f Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build.make Source/Core/VideoCommon/CMakeFiles/videocommon.dir/build
.PHONY : videocommon/fast

#=============================================================================
# Target rules for targets named videoogl

# Build rule for target.
videoogl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videoogl
.PHONY : videoogl

# fast build rule for target.
videoogl/fast:
	$(MAKE) -f Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/build.make Source/Core/VideoBackends/OGL/CMakeFiles/videoogl.dir/build
.PHONY : videoogl/fast

#=============================================================================
# Target rules for targets named videonull

# Build rule for target.
videonull: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videonull
.PHONY : videonull

# fast build rule for target.
videonull/fast:
	$(MAKE) -f Source/Core/VideoBackends/Null/CMakeFiles/videonull.dir/build.make Source/Core/VideoBackends/Null/CMakeFiles/videonull.dir/build
.PHONY : videonull/fast

#=============================================================================
# Target rules for targets named videosoftware

# Build rule for target.
videosoftware: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videosoftware
.PHONY : videosoftware

# fast build rule for target.
videosoftware/fast:
	$(MAKE) -f Source/Core/VideoBackends/Software/CMakeFiles/videosoftware.dir/build.make Source/Core/VideoBackends/Software/CMakeFiles/videosoftware.dir/build
.PHONY : videosoftware/fast

#=============================================================================
# Target rules for targets named dolphin-nogui

# Build rule for target.
dolphin-nogui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dolphin-nogui
.PHONY : dolphin-nogui

# fast build rule for target.
dolphin-nogui/fast:
	$(MAKE) -f Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/build.make Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui.dir/build
.PHONY : dolphin-nogui/fast

#=============================================================================
# Target rules for targets named dolphin-nogui_nro

# Build rule for target.
dolphin-nogui_nro: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dolphin-nogui_nro
.PHONY : dolphin-nogui_nro

# fast build rule for target.
dolphin-nogui_nro/fast:
	$(MAKE) -f Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui_nro.dir/build.make Source/Core/DolphinNoGUI/CMakeFiles/dolphin-nogui_nro.dir/build
.PHONY : dolphin-nogui_nro/fast

#=============================================================================
# Target rules for targets named unittests_main

# Build rule for target.
unittests_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests_main
.PHONY : unittests_main

# fast build rule for target.
unittests_main/fast:
	$(MAKE) -f Source/UnitTests/CMakeFiles/unittests_main.dir/build.make Source/UnitTests/CMakeFiles/unittests_main.dir/build
.PHONY : unittests_main/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f Source/UnitTests/CMakeFiles/unittests.dir/build.make Source/UnitTests/CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named unittests_stubhost

# Build rule for target.
unittests_stubhost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests_stubhost
.PHONY : unittests_stubhost

# fast build rule for target.
unittests_stubhost/fast:
	$(MAKE) -f Source/UnitTests/CMakeFiles/unittests_stubhost.dir/build.make Source/UnitTests/CMakeFiles/unittests_stubhost.dir/build
.PHONY : unittests_stubhost/fast

#=============================================================================
# Target rules for targets named SPSCQueueTest

# Build rule for target.
SPSCQueueTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SPSCQueueTest
.PHONY : SPSCQueueTest

# fast build rule for target.
SPSCQueueTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/SPSCQueueTest.dir/build.make Source/UnitTests/Common/CMakeFiles/SPSCQueueTest.dir/build
.PHONY : SPSCQueueTest/fast

#=============================================================================
# Target rules for targets named CryptoSHA1Test

# Build rule for target.
CryptoSHA1Test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CryptoSHA1Test
.PHONY : CryptoSHA1Test

# fast build rule for target.
CryptoSHA1Test/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/CryptoSHA1Test.dir/build.make Source/UnitTests/Common/CMakeFiles/CryptoSHA1Test.dir/build
.PHONY : CryptoSHA1Test/fast

#=============================================================================
# Target rules for targets named CommonFuncsTest

# Build rule for target.
CommonFuncsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CommonFuncsTest
.PHONY : CommonFuncsTest

# fast build rule for target.
CommonFuncsTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/CommonFuncsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/CommonFuncsTest.dir/build
.PHONY : CommonFuncsTest/fast

#=============================================================================
# Target rules for targets named CryptoEcTest

# Build rule for target.
CryptoEcTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CryptoEcTest
.PHONY : CryptoEcTest

# fast build rule for target.
CryptoEcTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/CryptoEcTest.dir/build.make Source/UnitTests/Common/CMakeFiles/CryptoEcTest.dir/build
.PHONY : CryptoEcTest/fast

#=============================================================================
# Target rules for targets named BusyLoopTest

# Build rule for target.
BusyLoopTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BusyLoopTest
.PHONY : BusyLoopTest

# fast build rule for target.
BusyLoopTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/BusyLoopTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BusyLoopTest.dir/build
.PHONY : BusyLoopTest/fast

#=============================================================================
# Target rules for targets named BitFieldTest

# Build rule for target.
BitFieldTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BitFieldTest
.PHONY : BitFieldTest

# fast build rule for target.
BitFieldTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/BitFieldTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitFieldTest.dir/build
.PHONY : BitFieldTest/fast

#=============================================================================
# Target rules for targets named EnumFormatterTest

# Build rule for target.
EnumFormatterTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EnumFormatterTest
.PHONY : EnumFormatterTest

# fast build rule for target.
EnumFormatterTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/EnumFormatterTest.dir/build.make Source/UnitTests/Common/CMakeFiles/EnumFormatterTest.dir/build
.PHONY : EnumFormatterTest/fast

#=============================================================================
# Target rules for targets named BitSetTest

# Build rule for target.
BitSetTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BitSetTest
.PHONY : BitSetTest

# fast build rule for target.
BitSetTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/BitSetTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitSetTest.dir/build
.PHONY : BitSetTest/fast

#=============================================================================
# Target rules for targets named BlockingLoopTest

# Build rule for target.
BlockingLoopTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockingLoopTest
.PHONY : BlockingLoopTest

# fast build rule for target.
BlockingLoopTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/BlockingLoopTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BlockingLoopTest.dir/build
.PHONY : BlockingLoopTest/fast

#=============================================================================
# Target rules for targets named StringUtilTest

# Build rule for target.
StringUtilTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 StringUtilTest
.PHONY : StringUtilTest

# fast build rule for target.
StringUtilTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/StringUtilTest.dir/build.make Source/UnitTests/Common/CMakeFiles/StringUtilTest.dir/build
.PHONY : StringUtilTest/fast

#=============================================================================
# Target rules for targets named BitUtilsTest

# Build rule for target.
BitUtilsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BitUtilsTest
.PHONY : BitUtilsTest

# fast build rule for target.
BitUtilsTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/BitUtilsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/BitUtilsTest.dir/build
.PHONY : BitUtilsTest/fast

#=============================================================================
# Target rules for targets named FileUtilTest

# Build rule for target.
FileUtilTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileUtilTest
.PHONY : FileUtilTest

# fast build rule for target.
FileUtilTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/FileUtilTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FileUtilTest.dir/build
.PHONY : FileUtilTest/fast

#=============================================================================
# Target rules for targets named FlagTest

# Build rule for target.
FlagTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlagTest
.PHONY : FlagTest

# fast build rule for target.
FlagTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/FlagTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FlagTest.dir/build
.PHONY : FlagTest/fast

#=============================================================================
# Target rules for targets named FixedSizeQueueTest

# Build rule for target.
FixedSizeQueueTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FixedSizeQueueTest
.PHONY : FixedSizeQueueTest

# fast build rule for target.
FixedSizeQueueTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/FixedSizeQueueTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FixedSizeQueueTest.dir/build
.PHONY : FixedSizeQueueTest/fast

#=============================================================================
# Target rules for targets named MathUtilTest

# Build rule for target.
MathUtilTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MathUtilTest
.PHONY : MathUtilTest

# fast build rule for target.
MathUtilTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/MathUtilTest.dir/build.make Source/UnitTests/Common/CMakeFiles/MathUtilTest.dir/build
.PHONY : MathUtilTest/fast

#=============================================================================
# Target rules for targets named FloatUtilsTest

# Build rule for target.
FloatUtilsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FloatUtilsTest
.PHONY : FloatUtilsTest

# fast build rule for target.
FloatUtilsTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/FloatUtilsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/FloatUtilsTest.dir/build
.PHONY : FloatUtilsTest/fast

#=============================================================================
# Target rules for targets named NandPathsTest

# Build rule for target.
NandPathsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NandPathsTest
.PHONY : NandPathsTest

# fast build rule for target.
NandPathsTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/NandPathsTest.dir/build.make Source/UnitTests/Common/CMakeFiles/NandPathsTest.dir/build
.PHONY : NandPathsTest/fast

#=============================================================================
# Target rules for targets named EventTest

# Build rule for target.
EventTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EventTest
.PHONY : EventTest

# fast build rule for target.
EventTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/EventTest.dir/build.make Source/UnitTests/Common/CMakeFiles/EventTest.dir/build
.PHONY : EventTest/fast

#=============================================================================
# Target rules for targets named SwapTest

# Build rule for target.
SwapTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SwapTest
.PHONY : SwapTest

# fast build rule for target.
SwapTest/fast:
	$(MAKE) -f Source/UnitTests/Common/CMakeFiles/SwapTest.dir/build.make Source/UnitTests/Common/CMakeFiles/SwapTest.dir/build
.PHONY : SwapTest/fast

#=============================================================================
# Target rules for targets named PageFaultTest

# Build rule for target.
PageFaultTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PageFaultTest
.PHONY : PageFaultTest

# fast build rule for target.
PageFaultTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/PageFaultTest.dir/build.make Source/UnitTests/Core/CMakeFiles/PageFaultTest.dir/build
.PHONY : PageFaultTest/fast

#=============================================================================
# Target rules for targets named DSPAssemblyTest

# Build rule for target.
DSPAssemblyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DSPAssemblyTest
.PHONY : DSPAssemblyTest

# fast build rule for target.
DSPAssemblyTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/DSPAssemblyTest.dir/build.make Source/UnitTests/Core/CMakeFiles/DSPAssemblyTest.dir/build
.PHONY : DSPAssemblyTest/fast

#=============================================================================
# Target rules for targets named ESFormatsTest

# Build rule for target.
ESFormatsTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ESFormatsTest
.PHONY : ESFormatsTest

# fast build rule for target.
ESFormatsTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/ESFormatsTest.dir/build.make Source/UnitTests/Core/CMakeFiles/ESFormatsTest.dir/build
.PHONY : ESFormatsTest/fast

#=============================================================================
# Target rules for targets named CoreTimingTest

# Build rule for target.
CoreTimingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CoreTimingTest
.PHONY : CoreTimingTest

# fast build rule for target.
CoreTimingTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/CoreTimingTest.dir/build.make Source/UnitTests/Core/CMakeFiles/CoreTimingTest.dir/build
.PHONY : CoreTimingTest/fast

#=============================================================================
# Target rules for targets named MMIOTest

# Build rule for target.
MMIOTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MMIOTest
.PHONY : MMIOTest

# fast build rule for target.
MMIOTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/MMIOTest.dir/build.make Source/UnitTests/Core/CMakeFiles/MMIOTest.dir/build
.PHONY : MMIOTest/fast

#=============================================================================
# Target rules for targets named FileSystemTest

# Build rule for target.
FileSystemTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FileSystemTest
.PHONY : FileSystemTest

# fast build rule for target.
FileSystemTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/FileSystemTest.dir/build.make Source/UnitTests/Core/CMakeFiles/FileSystemTest.dir/build
.PHONY : FileSystemTest/fast

#=============================================================================
# Target rules for targets named PowerPCTest

# Build rule for target.
PowerPCTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PowerPCTest
.PHONY : PowerPCTest

# fast build rule for target.
PowerPCTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/PowerPCTest.dir/build.make Source/UnitTests/Core/CMakeFiles/PowerPCTest.dir/build
.PHONY : PowerPCTest/fast

#=============================================================================
# Target rules for targets named DSPAcceleratorTest

# Build rule for target.
DSPAcceleratorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DSPAcceleratorTest
.PHONY : DSPAcceleratorTest

# fast build rule for target.
DSPAcceleratorTest/fast:
	$(MAKE) -f Source/UnitTests/Core/CMakeFiles/DSPAcceleratorTest.dir/build.make Source/UnitTests/Core/CMakeFiles/DSPAcceleratorTest.dir/build
.PHONY : DSPAcceleratorTest/fast

#=============================================================================
# Target rules for targets named VertexLoaderTest

# Build rule for target.
VertexLoaderTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VertexLoaderTest
.PHONY : VertexLoaderTest

# fast build rule for target.
VertexLoaderTest/fast:
	$(MAKE) -f Source/UnitTests/VideoCommon/CMakeFiles/VertexLoaderTest.dir/build.make Source/UnitTests/VideoCommon/CMakeFiles/VertexLoaderTest.dir/build
.PHONY : VertexLoaderTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... rebuild_cache"
	@echo "... package_source"
	@echo "... edit_cache"
	@echo "... cpp-optparse"
	@echo "... fmt"
	@echo "... imgui"
	@echo "... implot"
	@echo "... glslang"
	@echo "... pugixml"
	@echo "... enet"
	@echo "... xxhash"
	@echo "... bzip2"
	@echo "... lzma"
	@echo "... zstd"
	@echo "... zlib"
	@echo "... minizip"
	@echo "... lzo2"
	@echo "... spng"
	@echo "... FreeSurround"
	@echo "... SoundTouch"
	@echo "... cubeb"
	@echo "... speex"
	@echo "... sfml-network"
	@echo "... sfml-system"
	@echo "... lib"
	@echo "... mbedtls"
	@echo "... mbedx509"
	@echo "... mbedcrypto"
	@echo "... iconv"
	@echo "... FatFs"
	@echo "... rcheevos"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... audiocommon"
	@echo "... common"
	@echo "... core"
	@echo "... discio"
	@echo "... inputcommon"
	@echo "... uicommon"
	@echo "... videocommon"
	@echo "... videoogl"
	@echo "... videonull"
	@echo "... videosoftware"
	@echo "... dolphin-nogui"
	@echo "... dolphin-nogui_nro"
	@echo "... unittests_main"
	@echo "... unittests"
	@echo "... unittests_stubhost"
	@echo "... SPSCQueueTest"
	@echo "... CryptoSHA1Test"
	@echo "... CommonFuncsTest"
	@echo "... CryptoEcTest"
	@echo "... BusyLoopTest"
	@echo "... BitFieldTest"
	@echo "... EnumFormatterTest"
	@echo "... BitSetTest"
	@echo "... BlockingLoopTest"
	@echo "... StringUtilTest"
	@echo "... BitUtilsTest"
	@echo "... FileUtilTest"
	@echo "... FlagTest"
	@echo "... FixedSizeQueueTest"
	@echo "... MathUtilTest"
	@echo "... FloatUtilsTest"
	@echo "... NandPathsTest"
	@echo "... EventTest"
	@echo "... SwapTest"
	@echo "... PageFaultTest"
	@echo "... DSPAssemblyTest"
	@echo "... ESFormatsTest"
	@echo "... CoreTimingTest"
	@echo "... MMIOTest"
	@echo "... FileSystemTest"
	@echo "... PowerPCTest"
	@echo "... DSPAcceleratorTest"
	@echo "... VertexLoaderTest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

